// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuqC1tvzrVHTCgz0mw717FBr0oA7eKTsA',
    appId: '1:464295412559:web:0032267889362e6dd77b3a',
    messagingSenderId: '464295412559',
    projectId: 'appademics-2b1cb',
    authDomain: 'appademics-2b1cb.firebaseapp.com',
    databaseURL: 'https://appademics-2b1cb-default-rtdb.firebaseio.com',
    storageBucket: 'appademics-2b1cb.firebasestorage.app',
    measurementId: 'G-NCRW179X4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf-ys0-vfcRlHq9mxRndM5s6P63AB2Xho',
    appId: '1:464295412559:android:e0030ad9934c1208d77b3a',
    messagingSenderId: '464295412559',
    projectId: 'appademics-2b1cb',
    databaseURL: 'https://appademics-2b1cb-default-rtdb.firebaseio.com',
    storageBucket: 'appademics-2b1cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC7zbxWiacD2e5_Wo2fCKv25Ln9kltm3Q',
    appId: '1:464295412559:ios:22bd526a3e434818d77b3a',
    messagingSenderId: '464295412559',
    projectId: 'appademics-2b1cb',
    databaseURL: 'https://appademics-2b1cb-default-rtdb.firebaseio.com',
    storageBucket: 'appademics-2b1cb.firebasestorage.app',
    iosBundleId: 'com.example.appademics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC7zbxWiacD2e5_Wo2fCKv25Ln9kltm3Q',
    appId: '1:464295412559:ios:22bd526a3e434818d77b3a',
    messagingSenderId: '464295412559',
    projectId: 'appademics-2b1cb',
    databaseURL: 'https://appademics-2b1cb-default-rtdb.firebaseio.com',
    storageBucket: 'appademics-2b1cb.firebasestorage.app',
    iosBundleId: 'com.example.appademics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuqC1tvzrVHTCgz0mw717FBr0oA7eKTsA',
    appId: '1:464295412559:web:fcf284a553497e1ed77b3a',
    messagingSenderId: '464295412559',
    projectId: 'appademics-2b1cb',
    authDomain: 'appademics-2b1cb.firebaseapp.com',
    databaseURL: 'https://appademics-2b1cb-default-rtdb.firebaseio.com',
    storageBucket: 'appademics-2b1cb.firebasestorage.app',
    measurementId: 'G-85RJCXG7EM',
  );

  
}